apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-cluster-admin
rules:
- apiGroups: 
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-cluster-admin
  namespace: default
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: namespace-cluster-admin
  apiGroup: rbac.authorization.k8s.io